tags:
  discounts-green: false
  products-green: false
  discountsNetworkingOffline: false
  productsNetworkingOffline: false

discounts-blue:
  mode: online
  quarkus-base:
    fullnameOverride: "discounts"
    image:
      tag: v1.0.1
    version: none
    rollouts:
      enabled: true
      canary:
        steps:
          - setWeight: 50
          - pause:
              duration: 1m
  fullnameOverride: "discounts"
    
products-blue:
  mode: online
  quarkus-base:
    image:
      tag: v1.0.1
    version: none
    replicaCount: 4
    fullnameOverride: "products"
    rollouts:
      enabled: true
      canary:
        steps:
          - setWeight: 25
          - pause:
              duration: 300s
          - setWeight: 50
          - pause:
              duration: 300s
  fullnameOverride: "products"
  
global:
  namespace: test
  #needed for rollouts analysis









